# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VU-X-c3c8OtN8eMHaRokg0mwed9P3ZFU
"""

!git clone https://github.com/THU-MIG/yolov10.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10
!pip install -q -r requirements.txt
!pip install -e .

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10n.pt

from ultralytics import YOLOv10

MODEL_PATH = 'yolov10n.pt'

model = YOLOv10(MODEL_PATH)

! gdown '1tr9PSRRdlC2pNir7jsYugpSMG-7v32VJ' -O ''./images/''

IMG_PATH ='./images/HCMC_Street.jpg'
result = model(source=IMG_PATH)[0]

result.save('./images/HCMC_Street_predict.png')

!gdown '1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R'

!gdown '1twdtZEfcw4ghSZIiPDypJurZnNXzMO7R'
#!mkdir safety_helmet_dataset
!unzip -q '/content/yolov10/Safety_Helmet_Dataset.zip' -d '/content/yolov10/safety_helmet_dataset'

YAML_PATH = '/content/yolov10/safety_helmet_dataset/data.yaml'
EPOCHS = 50
IMG_SIZE = 640
BATCH_SIZE = 256

model.train(data=YAML_PATH,
            epochs=EPOCHS,
            imgsz=IMG_SIZE,
            batch=BATCH_SIZE)